# Generated by Django 3.2.8 on 2023-04-29 10:49

import avatar.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0015_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=avatar.models.AvatarField(),
        ),
    ]
