# Generated by Django 3.2.8 on 2023-05-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0016_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('in_progress', 'In Progress')], default='in_progress', max_length=20),
        ),
    ]
